name: Provision EC2 with Ansible

#on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible, boto3, and botocore
        run: |
          /usr/bin/python3 -m pip install --upgrade pip
          /usr/bin/python3 -m pip install ansible boto3 botocore

      - name: Check boto3 and botocore installation
        run: |
          /usr/bin/python3 -m pip show boto3
          /usr/bin/python3 -m pip show botocore

      - name: Install required Ansible collections
        run: ansible-galaxy collection install amazon.aws community.aws

      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > vault-pass.txt
          ansible-playbook -i inventory/hosts.yml site.yml --vault-password-file vault-pass.txt
          rm vault-pass.txt

      - name: Output Ansible Playbook Result
        run: echo "${{ steps.ansible-playbook.outputs.stdout }}"
