name: Provision EC2 with Ansible and run Ansible Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible, boto3, botocore, and Ansible Lint
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible boto3 botocore ansible-lint

      # This step will run ansible-lint but won't fail the workflow if issues are found
      - name: Run Ansible Lint
        continue-on-error: true
        run: ansible-lint site.yml roles/ || true

      # Install necessary Ansible collections
      - name: Install required Ansible collections
        run: ansible-galaxy collection install amazon.aws community.aws

      # Execute the Ansible playbook with the vault password
      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > vault-pass.txt
          ansible-playbook -i inventory/hosts.yml site.yml --vault-password-file vault-pass.txt
          rm vault-pass.txt

      # Output the result of the Ansible playbook execution
      - name: Output Ansible Playbook Result
        run: echo "${{ steps.ansible-playbook.outputs.stdout }}"
